### ISSUE TITLE
Not generating all color values

### ISSUE THREAD

**Issue by groschi24** [wtho/bulma-css-vars#20]
When I generate the files from my config not all colors are in the generated files.

Config file:
```javascript
const { hsl } = require('bulma-css-vars');

const appColors = {
  black: hsl(0, 0, 4),
  'black-bis': hsl(0, 0, 7),
  'black-ter': hsl(0, 0, 14),
  'grey-darker': '#8a8f9c',
};

module.exports = {
  jsOutputFile: 'src/bulma-generated/bulma-colors.js',
  sassOutputFile: 'src/bulma-generated/generated-bulma-vars.sass',
  cssFallbackOutputFile: 'src/bulma-generated/generated-fallback.css',
  colorDefs: appColors,
  sassEntryFile: 'src/main.scss',
  transition: '0.3s ease',
};
```

Output:
```javascript

module.exports = {
  "bulmaCssVariablesDefs": {
    "black": {
      "calls": [
        {
          "fn": "rgba",
          "fnArg": "10",
          "composeArg": null
        },
        {
          "fn": "rgba",
          "fnArg": "2",
          "composeArg": null
        },
        {
          "fn": "rgba",
          "fnArg": "20",
          "composeArg": null
        },
        {
          "fn": "rgba",
          "fnArg": "5",
          "composeArg": null
        },
        {
          "fn": "lighten",
          "fnArg": "800",
          "composeArg": null
        }
      ]
    },
    "grey-darker": {
      "calls": [
        {
          "fn": "lighten",
          "fnArg": "800",
          "composeArg": null
        },
        {
          "fn": "color-invert",
          "fnArg": null,
          "composeArg": null
        }
      ]
    }
  }
}
```

So I add `black` `black-bis` `black-ter` but only `black` gets generated and `grey-darker` works

**Comment by wtho** [comment]
Yeah, just realised bulma's utility was expanded by `helpers.sass` which is not loaded yet in `bulma-css-vars`. I will fix this in the next version, then you can use bulma v0.9 without issues.

**Comment by wtho** [comment]
Just released v0.5.0, please check if this resolves your issue.

Cheers and happy coding!

**Comment by wtho** [comment]
@Tim-Machine `$scheme-invert` works for me:
```js
const { rgb } = require('bulma-css-vars')

const appColors = {
  'scheme-invert': rgb(255, 123, 100),
}
// module.exports = { ... }
```
After regenerating and using a modal with a `modal-background` to cover the page, it tints everything in a nice red.

I also could find the variable being used on the modal background:
```css
.modal-background {
    background-color: var(--scheme-invert--86--rgba);
}
:root {
    --scheme-invert--10--rgba: rgba(255, 123, 100, 0.1);
    --scheme-invert--2--rgba: rgba(255, 123, 100, 0.02);
    --scheme-invert--20--rgba: rgba(255, 123, 100, 0.2);
    --scheme-invert--30--rgba: rgba(255, 123, 100, 0.3);
    --scheme-invert--40--rgba: rgba(255, 123, 100, 0.4);
    --scheme-invert--5--rgba: rgba(255, 123, 100, 0.05);
    --scheme-invert--86--rgba: rgba(255, 123, 100, 0.86);
}
```
Notice that most `scheme-invert` variables are quite transparent, `.modal-background` being the only one having a value over 0.4.

Maybe you can create a small reproduction of your error on github so I can have a look at it?
