### ISSUE TITLE
Missing Hover and Focus States

### ISSUE THREAD

**Issue by drewalth** [wtho/bulma-css-vars#21]
Hover and Focus state styles are missing.

#### Config

```js
const appColors = {
  success: '#48c774'
}
```

#### Hover
```css
.button.is-success:hover, .button.is-success.is-hovered {
    background-color: var(--success);
    border-color: transparent;
    color: var(--success--color-invert);
}
```

#### Focus
```css
.button.is-success:focus:not(:active), .button.is-success.is-focused:not(:active) {
    box-shadow: 0 0 0 0.125em var(--success);
}
```

### Expected Behavior

Hover colors should be a little darker. Focus colors should be rgba values.

#### Base
```css
.button.is-success {
    background-color: #48c774;
    border-color: transparent;
    color: #fff;
}
```

#### Hover
```css
.button.is-success:hover, .button.is-success.is-hovered {
    background-color: #3ec46d;
    border-color: transparent;
    color: #fff;
}
```

#### Focus
```css
.button.is-success:focus:not(:active), .button.is-success.is-focused:not(:active) {
    box-shadow: 0 0 0 0.125em rgba(72, 199, 116, 0.25);
}
```

### Potential Solution

I was able to kind of fix this manually for a few elements but it would be way better if this could happen automagically.

```scss
// _my-project-variables.scss

@import '~/bulma/sass/utilities/functions.sass';
@import '~/bulma-css-vars/functions.sass';

$links: var(--links);

$input-focus-box-shadow-color: rgba($links, 0.25);
$button-focus-box-shadow-color: rgba($links, 0.25);
```

```js
// theme-controller.js
// I am manually adding styles. This is probably not the cleanest way but it works...

let themeConfig = ':root {'

themeConfig += `--success--25--rgba: ${bulmaColorTools.rgba('#48c774', 25)};`

themeConfig += '}'

// style tag in index.html
document.getElementById('themeConfig').innerHTML = themeConfig;

```

```css
/* patch-styles.css */

.button.is-success:focus:not(:active), .button.is-success.is-focused:not(:active) {
  box-shadow: 0 0 0 .125em var(--success--25--rgba);
}
```

Thanks! This is an awesome package.
